apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-django
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.django.service.type }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    component: django
  sessionAffinity: None
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: {{ .Values.django.service.port }} 