apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-postgres
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    component: postgres
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }} 