apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-postgres-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }} 