# Generated by Django 5.1.4 on 2024-12-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="suggested_answer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
